---
abstract: 'Pure Perl Implementation of the Rijndael Cipher'
author:
  - 'Robert Stone <drzigman@cpan.org>'
build_requires:
  Crypt::CBC: '0'
  Crypt::Rijndael: '0'
  File::Spec: '0'
  FindBin: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Module::Build: '0.28'
  MooseX::Params::Validate: '0'
  Storable: '0'
  String::Random: '0'
  Test::Exception: '0'
  Test::More: '0'
  lib: '0'
  perl: '5.010'
configure_requires:
  Module::Build: '0.28'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.025, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Crypt-Rinjdael-PP
requires:
  Carp: '0'
  Crypt::Random::Source: '0'
  Data::Dumper: '0'
  Exporter: '0'
  Readonly: '0'
  Smart::Comments: '0'
  bytes: '0'
  perl: '5.010'
resources:
  bugtracker: https://github.com/drzigman/crypt-rinjdael-pp/issues
  homepage: http://search.cpan.org/dist/Crypt-Rinjdael-PP
  repository: git://github.com/drzigman/crypt-rinjdael-pp.git
version: 0.1.0
